version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    # Corrected 'environment' section using the dictionary/map syntax.
    # Note the absence of the '-' hyphen.
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: gemma-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build: ./app
    container_name: nl-to-sql-app
    restart: always
    ports:
      - "8000:8000"
    # Also corrected the 'app' service's environment for consistency.
    environment:
      DB_HOST: db
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password}
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started

  # --- NEW UI SERVICE ---
  ui:
    build: ./ui
    container_name: sqlingua-ui
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - app

volumes:
  pgdata:
  ollama_data: